#!/usr/bin/env python3
"""A new class in the Cache method."""
import redis
import uuid
from typing import Union
from functools import wraps
import requests

class Cache:
    def __init__(self):
        """flush all data in the redis database."""
        self._redis = redis.Redis()
        # flush the database
        self._redis.flushdb()

    def store(self, data: Union[str, bytes, int, float]) -> str:
        """store data in Redis and return an autogenerated key."""

        random_key = str(uuid.uuid4())
        self._redis.set(random_key, data)
        return random_key
